# Basic
title: 行走东瀛
subtitle: 樊昕的个人网站
welcome_message: <a href="https://github.com/fan-xin" target="_blank">Visit My GitHub</a>
description: 
creator: <a href="http://github/fan-xin">@fanxinshr</a>

url: "http://fan-xin.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate 

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: APP开发, description: My Projects, url: 'http://github/fan-xin'}
    - {title: 网站制作, description: WebSite, url: 'half-slider-gh-pages'}
    - {title: 简历, description: 了解更多关于我, url: 'https://github.com/fan-xin/Resume'}
    - {title: 订阅, description: 邮件订阅本站, url: ''}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: fanxinshr
    # duoshuo: 
    
# Social
social:
    weibo: fanxinshr
    github: fan-xin
    twitter: fanxinshr
    gplus: fanxinshr
    mail: fanxin.hit@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
